prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix GO: <http://purl.obolibrary.org/obo/GO_>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix in_taxon: <http://purl.obolibrary.org/obo/RO_0002162>
prefix never_in_taxon: <http://purl.obolibrary.org/obo/RO_0002161>

CONSTRUCT
  {?c owl:disjointWith [
    a owl:Restriction ;
    owl:onProperty in_taxon: ;
    owl:someValuesFrom ?t
   ]
  }
WHERE {?c never_in_taxon: ?t }
