# # Duplicate Label
#
# Problem: Two different subjects have been assigned the same label. This causes ambiguity.
#
# Solution: Avoid ambiguity by assigning distinct labels to each subject.

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?entity ?property ?value WHERE {
  VALUES ?property {rdfs:label}
  ?entity ?property ?value .
  ?entity2 ?property ?value .
  FILTER (?entity != ?entity2)
  FILTER (!isBlank(?entity))
  FILTER NOT EXISTS {
    ?entity owl:deprecated true .
  }
}
ORDER BY DESC(UCASE(str(?value)))
