PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX metago: <http://model.geneontology.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT ?c ?oneSynonym ?anotherSynonym ?syn
WHERE {

    VALUES ?oneSynonym {
        oboInOwl:hasSynonym
        oboInOwl:hasExactSynonym
        oboInOwl:hasNarrowSynonym
        oboInOwl:hasBroadSynonym
        oboInOwl:hasRelatedSynonym
    }

    VALUES ?anotherSynonym {
        oboInOwl:hasSynonym
        oboInOwl:hasExactSynonym
        oboInOwl:hasNarrowSynonym
        oboInOwl:hasBroadSynonym
        oboInOwl:hasRelatedSynonym
    }

    ?c ?oneSynonym ?syn1 .
    ?c ?anotherSynonym ?syn2 .
    
    FILTER(LCASE(?syn1) = LCASE(?syn2))

    FILTER NOT EXISTS {
        ?c owl:deprecated true .
    }
    FILTER (STR(?anotherSynonym) < STR(?oneSynonym))
}
