prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix GO: <http://purl.obolibrary.org/obo/GO_>
prefix part_of: <http://purl.obolibrary.org/obo/BFO_0000050>
prefix regulates: <http://purl.obolibrary.org/obo/RO_0002211>
prefix positively_regulates: <http://purl.obolibrary.org/obo/RO_0002213>
prefix negatively_regulates: <http://purl.obolibrary.org/obo/RO_0002212>


SELECT DISTINCT ?term ?p1 ?c
WHERE {
  # GO:0046425
  VALUES ?p1 { part_of: regulates: positively_regulates: negatively_regulates: }
  VALUES ?p2 { part_of: regulates: positively_regulates: negatively_regulates: }
  ?term rdfs:subClassOf ?rest1 .
  ?term rdfs:subClassOf ?rest2 .
  FILTER(?rest1 != ?rest2)
  ?rest1 owl:someValuesFrom ?c .
  ?rest2 owl:someValuesFrom ?c .
  ?rest1 owl:onProperty ?p1 .
  ?rest2 owl:onProperty ?p2 .
  FILTER(?p1 < ?p2)
}
ORDER BY ASC(?term)
