PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://purl.uniprot.org/core/>
SELECT DISTINCT ?ec ?obsolete
WHERE {
  ?enzyme rdf:type :Enzyme .
  OPTIONAL { ?enzyme :obsolete ?obs . }
  BIND(COALESCE(?obs, false) AS ?obsolete)
  BIND(REPLACE(STR(?enzyme), "http://purl.uniprot.org/enzyme/", "EC:") AS ?ec)
}
