PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX metago: <http://model.geneontology.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?c1 ?n ?c2
WHERE {
    ?c1 <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> ?n .
    ?c2 <http://www.w3.org/2000/01/rdf-schema#label> ?n .

    FILTER(isURI(?c1))
    FILTER(isURI(?c2))
    FILTER NOT EXISTS {
        ?c1 owl:deprecated true .
    }
    FILTER NOT EXISTS {
        ?c2 owl:deprecated true .
    }
    FILTER (?c1 != ?c2)
}
