pattern_name: molecular function activator activity

pattern_iri: http://purl.obolibrary.org/obo/go/patterns/activator_activity.yaml

description: This pattern is for representing a function that activates some molecular function, differentiated by the specific molecular function activated.

classes:
  molecular function regulator activity: 'GO:0098772'
  catalytic activity: 'GO:0003824'

relations:
  positively regulates: 'RO:0002213' 
  
vars:
  regulated_activity: "'catalytic activity'" 

substitutions:
   - 
     in: regulated_activity
     out: regulated_activity_munged
     match: "(.+) activity"
     sub: '\1'  

data_list_vars:
  def_dbxrefs: "xsd:string"
  
name:
  text: "%s activator activity"
  vars:   
    - 'regulated_activity_munged'
    
def: 
  text: "Binds to and increases the activity of %s."
  vars:
    - 'regulated_activity'

namespace: 
  text: 'molecular_function'

equivalentTo: 
  text: "'molecular function regulator activity' and 'directly positively regulates' some %s" 
  vars:
    - 'regulated_activity'
