name: Update taxon constraints

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:${{ vars.ODK_VERSION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Work around https://github.com/peter-evans/create-pull-request/issues/1170
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Update taxon constraints
        run: touch src/taxon_constraints/present_in_taxon.tsv && cd src/ontology && make ../taxon_constraints/present_in_taxon_annotations.ofn && cd ../..

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update taxon constraints
          branch: update-taxon-constraints
          add-paths: |
            src/taxon_constraints/present_in_taxon.ofn
            src/taxon_constraints/present_in_taxon_annotations.ofn
          token: ${{ secrets.PR_ACTION_TOKEN }}
